version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: schoolflex_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: schoolflex_db
      MYSQL_USER: schoolflex_user
      MYSQL_PASSWORD: schoolflex_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: